[phases.setup]
nixPkgs = ['...', 'nodejs', 'yarn']
aptPkgs = ["libfontconfig", "libfontconfig1", "libfontconfig1-dev", "libxrender-dev", "fontconfig", "build-essential", "gcc"]

[start]
  runImage = 'ubuntu:jammy'