minimumReleaseAge: 10080
blockExoticSubdeps: true
allowBuilds:
  bufferutil: true
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true
overrides:
  brace-expansion@1.x: ">=1.1.17"
  brace-expansion@2.x: ">=2.1.3"
